from __future__ import annotations

import tempfile
import unittest

from orx.config import resolve_runtime_paths
from orx.continuity import ContinuityService
from orx.executor import ExecutorService
from orx.linear_client import LinearCreatedIssue
from orx.mirror import LinearMirrorRepository
from orx.ownership import OwnershipService
from orx.proposal_materialization import ProposalMaterializationService
from orx.proposals import ProposalService
from orx.repository import OrxRepository
from orx.storage import Storage

from tests.test_executor import FakeTmuxTransport


class ProposalMaterializationServiceTests(unittest.TestCase):
    def test_materialize_leaf_ticket_proposal_is_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            storage, proposals, mirror, client = _materialization_fixture(temp_dir)
            proposal = proposals.route(
                "PRO-22",
                "runner-a",
                improvement_title="Refine proposal lifecycle CLI",
                context={"suggested_phase_issue_key": "PRO-10"},
            )
            service = ProposalMaterializationService(
                storage,
                proposals=proposals,
                mirror=mirror,
                client=client,
            )

            first = service.materialize(proposal_id=proposal.proposal_id)
            second = service.materialize(proposal_id=proposal.proposal_id)

            self.assertFalse(first.idempotent)
            self.assertTrue(second.idempotent)
            self.assertEqual(first.created_issue.identifier, "PRO-90")
            self.assertEqual(second.created_issue.identifier, "PRO-90")
            self.assertEqual(len(client.calls), 1)
            self.assertEqual(client.calls[0]["parent_id"], "phase-10")
            self.assertIn("Generated by ORX from `PRO-22`.", client.calls[0]["description"])
            self.assertEqual(first.proposal.status, "materialized")
            self.assertEqual(first.proposal.materialized_issue_identifier, "PRO-90")

    def test_materialize_rejects_non_leaf_ticket_proposals(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            storage, proposals, mirror, client = _materialization_fixture(temp_dir)
            proposal = proposals.route("PRO-22", "runner-a")
            service = ProposalMaterializationService(
                storage,
                proposals=proposals,
                mirror=mirror,
                client=client,
            )

            with self.assertRaisesRegex(ValueError, "cannot be materialized"):
                service.materialize(proposal_id=proposal.proposal_id)


class FakeLinearClient:
    def __init__(self) -> None:
        self.calls: list[dict[str, str | None]] = []

    def create_issue(
        self,
        *,
        team_id: str,
        title: str,
        description: str,
        parent_id: str | None = None,
        project_id: str | None = None,
    ) -> LinearCreatedIssue:
        self.calls.append(
            {
                "team_id": team_id,
                "title": title,
                "description": description,
                "parent_id": parent_id,
                "project_id": project_id,
            }
        )
        return LinearCreatedIssue(
            linear_id="issue-created-90",
            identifier="PRO-90",
            title=title,
            url="https://linear.example/PRO-90",
        )


def _materialization_fixture(
    temp_dir: str,
) -> tuple[Storage, ProposalService, LinearMirrorRepository, FakeLinearClient]:
    storage = Storage(resolve_runtime_paths(temp_dir))
    storage.bootstrap()
    repository = OrxRepository(storage)
    repository.upsert_runner(
        "runner-a",
        transport="tmux-codex",
        display_name="Runner A",
        state="idle",
    )
    executor = ExecutorService(
        storage=storage,
        repository=repository,
        ownership=OwnershipService(repository),
        transport=FakeTmuxTransport(),
    )
    request = executor.dispatch_slice(
        issue_key="PRO-22",
        runner_id="runner-a",
        objective="Route decomposition decisions from continuity",
        slice_goal="Persist proposal records",
        acceptance=["proposal stored"],
        validation_plan=["reload proposal from sqlite"],
        blockers=[],
    )
    executor.submit_slice_result(
        request.slice_id,
        {
            "status": "success",
            "summary": "Continuity state ready for proposal routing",
            "verified": True,
            "next_slice": "Persist proposal records",
            "artifacts": ["orx/proposals.py"],
            "metrics": {"proposals": 0},
        },
    )

    mirror = LinearMirrorRepository(storage)
    phase = mirror.upsert_issue(
        linear_id="phase-10",
        identifier="PRO-10",
        title="Phase 5",
        description="",
        team_id="team-1",
        team_name="Projects",
        state_name="In Progress",
        state_type="started",
        project_id="project-1",
        project_name="ORX",
        source_updated_at="2026-04-15T22:00:00+00:00",
    )
    mirror.upsert_issue(
        linear_id="leaf-22",
        identifier="PRO-22",
        title="Proposal routing",
        description="",
        team_id=phase.team_id,
        team_name=phase.team_name,
        state_name="In Progress",
        state_type="started",
        project_id=phase.project_id,
        project_name=phase.project_name,
        parent_linear_id=phase.linear_id,
        parent_identifier=phase.identifier,
        source_updated_at="2026-04-15T22:01:00+00:00",
    )

    proposals = ProposalService(storage, continuity=ContinuityService(storage))
    return storage, proposals, mirror, FakeLinearClient()


if __name__ == "__main__":
    unittest.main()
